### ISSUE TITLE
assertModulesLoaded not matching all loaded Modules

### ISSUE THREAD

**Issue by nusphere** [laminas/laminas-test#25]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.4.2

#### Summary
$modulesLoaded = array_keys($moduleManager->getLoadedModules());
#### Current behavior

assertModulesLoaded not matching all loaded Modules

#### How to reproduce

1. Add an internal dependency in a module (like 'Laminas\Mvc\I18n') with `InitProviderInterface`
2. assert for this Module with assertModulesLoaded()
 
#### Expected behavior

this will be true

**Comment by visto9259** [comment]
Was able to reproduce with latest version.
Assign to me and I will fix it
