### ISSUE TITLE
`assertTemplateName` returns too early

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-test#3]
`assertTemplateName` appears to return too early, and does not recursively search all child templates (see below).

```
<?php

public function myAction()
{
	$vm = new ViewModel();

	$child1 = (new ViewModel())->setTemplate('foo');
	$child2 = (new ViewModel())->setTemplate('bar');

	$vm->addChild($child1);
	$vm->addChild($child2);

	return $vm;
}

...

class testCase extends AbstractHttpControllerTestCase {
	
	public function testMyAction()
	{
		$this->dispatch('/my/action', 'GET', []);
		$this->assertTemplateName('foo'); // <-- true
		$this->assertTemplateName('bar'); // <-- false
	}

}
```

---

Originally posted by @SorX14 at https://github.com/zendframework/zend-test/issues/59

**Comment by visto9259** [comment]
This is a very old issue.
I was able to reproduce with the latest version.
When cycling through a view model that has more than one children, in this case 'child1' and 'child2', it will return early if 'child1' does not use the asserted template.
I am surprised that no one ever fixed this bug before.
Assigned it to me and I will fix it

**Comment by visto9259** [comment]
This is a very old issue but I was able to reproduce it with the latest version. 
The function `searchTemplates()` cycles through the tree of children correctly except when a view has more than one child where it returns early if the first child's template does not match the asserted template.
Assign it to me and I will fix it.
