### ISSUE TITLE
Module name is not recognized correctly in 3.5.0

### ISSUE THREAD

**Issue by FabianKoestring** [laminas/laminas-test#34]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.5.0

#### Summary

It looks like the changes in #21 don't really work.

#### Current behavior

We have a controller `Praktikumsangebot` in Module `Angebote` and Namespace `Angebote\Controller`. In a test we check with `$this->assertModuleName('Angebote');` if the module is `Angebote`. We also have a module `Praktikum`. In versions prior `3.5.0` the tests pass.

I checked `getCurrentModuleName()` in `IsCurrentModuleNameConstraint`. In version `3.5.0` it will return `praktikum`.

**Comment by FabianKoestring** [comment]
ping @nusphere

**Comment by nusphere** [comment]
i will have a look into it.

If I understand correctly, the controller is `\Angebote\Controller\Praktikumsangebot` and so the correct behavior `getCurrentModuleName('Angebote')` should be true.

It is important that this module is also stored as "Angebote". How ist your Module is registered in your Modules Setting in your Application?

**Comment by nusphere** [comment]
the `matches` method compares the module name to be checked (converted to strtolower) with the modules which are "registered" in the application. This is the "main method" of a PHPUnit Contraint.

**Comment by nusphere** [comment]
see https://github.com/laminas/laminas-test/blob/2347c8416f47b7d0a99cd8c15931ae450131c715/test/PHPUnit/Controller/AbstractControllerTestCaseTest.php#L181

The Test `testAssertModuleNameWithNamespace` works like the Method should work for a module like https://github.com/laminas/laminas-test/tree/2347c8416f47b7d0a99cd8c15931ae450131c715/test/_files/ModuleWithNamespace/TestModule . A modulename from a Module like Laminas\Barcode is "Barcode" so this behavior is solved. Please explain in Detail, why this implementation fails.

**Comment by FabianKoestring** [comment]
@nusphere see https://github.com/laminas/laminas-test/pull/36
Hopefully this example shows the problem

**Comment by nusphere** [comment]
thank you for this support. i will debug your testcases

**Comment by visto9259** [comment]
Did we forget to close this issue following the merge of #36?

**Comment by Xerkus** [comment]
Yeah. It should have been autoclosed.
