### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-test#40]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

PHP with [version 8.1 is released](https://www.php.net/releases/8.1/index.php) and for this component the support of the new version is still missing.

**Comment by Koen1999** [comment]
Perhaps it is useful to note that the dependency on laminas-console is an issue for support of PHP 8.0 and thus also for this next upgrade.

```
  Problem 1
    - laminas/laminas-console 2.6.0 requires php ^5.5 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
    - laminas/laminas-console[2.7.0, ..., 2.8.0] require php ^5.6 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
    - laminas/laminas-test 3.7.0 requires laminas/laminas-console ^2.6 -> satisfiable by laminas/laminas-console[2.6.0, 2.7.0, 2.8.0].
    - Root composer.json requires laminas/laminas-test ^3.7 -> satisfiable by laminas/laminas-test[3.7.0].
```

Edit: I just noticed this is already addressed in the 4.x branch.

**Comment by Ocramius** [comment]
Handled in #52
