### ISSUE TITLE
$_SERVER['REQUEST_URI'] not set after dispatch

### ISSUE THREAD

**Issue by Koen1999** [laminas/laminas-test#54]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.0.0

#### Summary

If you make use of `$_SERVER['REQUEST_URI']` in your code, or for example make use of the serverUrl view helper from laminas-view, then all unit tests using this functionality will fail because `$_SERVER['REQUEST_URI']` is not set.

#### Current behavior

`$_SERVER['REQUEST_URI']` is not set.

#### How to reproduce
Dispatch to some page making use of the serverUrl view helper. (https://github.com/laminas/laminas-view/blob/3.0.x/src/Helper/ServerUrl.php)
Observe the failing unit test.

#### Expected behavior
Unit test does not fail because `$_SERVER['REQUEST_URI']` is not set. The request URI should be set to a URI matching the dispatched route.

PS. Alternatively, this can be considered a bug in the laminas-view serverUrl view helper. Perhaps, it can be considered both.

**Comment by Ocramius** [comment]
This seems normal? `laminas/` libraries are nor supposed to mess with global state: you are responsible for doing that.

I would rather say that the view helper should probably not rely on global state either, but rather work with a request object.
