### ISSUE TITLE
[RFC]: PHPUnit 10 support

### ISSUE THREAD

**Issue by rohm1** [laminas/laminas-test#70]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 5.0.0  |
| BC Break?           | Yes |

### Goal

Upgrade the component to PHPUnit 10

### Considerations

PHPUnit dropped support for PHP 8.0 so we will have to drop it as well.

**Comment by froschdesign** [comment]
Fixed with #71 and released with [4.8.0](https://github.com/laminas/laminas-test/releases/tag/4.8.0).

**Comment by cooperaj** [comment]
So this is listed as a BC break and was proposed for 5.0 but was merged in at 4.8?

Does laminas-test follow semver?

**Comment by Ocramius** [comment]
Luckiy, no BC breaks in this package, in theory: inherited symbols weren't affected

**Comment by Ocramius** [comment]
@cooperaj where did you notice a BC break? :thinking:

**Comment by cooperaj** [comment]
Maybe nothing in this one but the hard dependency on PHPUnit 10 means [this list of deprecations](https://github.com/sebastianbergmann/phpunit/blob/9.6/DEPRECATIONS.md) comes into play? At least it has for us.

**Comment by Ocramius** [comment]
Yes, but you are supposed to depend on `phpunit/phpunit` to the version you rely upon, if you reference any phpunit symbol yourself :-)
