### ISSUE TITLE
Testing of SessionController.php fails because I get the wrong response data

### ISSUE THREAD

**Issue by swaitz** [laminas/laminas-test#83]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.7.0, 4.10.0

#### Summary

I'm trying to test an endpoint in our application. When I try to do that it fails becuase I get
the wrong result for the request. When I do this I get the response from the login request
which is fired before the request which I want to test.

#### How to reproduce
1) Make a POST request to a /login endpoint which returns a success and a jwt
2) use the jwt to make a GET request to /getSessionData endpoint
3) if you check the response data from the /getSessionData endpoint it will have the login data

The POST request to the /login endpoint is done in the setUp method of the 
BaseControllerTestCase which extends AbstractHttpControllerTestCase. The 
SessionControllerTest extends the BaseControllerTestCase and this class is run
with this comment tag runTestsInSeparateProcesses.

In my test case I do this:
```php
$this->dispatch('/getSessionData', 'GET', [
     'jwt'   => $this->jwt
]);
$this->assertResponseStatusCode(200);
       
// we get the login data here not the response from dispatch /getSessionData
$returnContent = Json::decode($this->getResponse()->getContent(), Json::TYPE_ARRAY);

// this is the part where it fails because there is no data array in the login request
$this->assertArrayHasKey('data', $returnContent);
```
I have also seen that the second dispatch call is not resetted correctly it still contains
the post data from the $this->dispatch('/login', 'POST')

#### Expected behavior

I would expect that I would get the correct reponse for my $this->dispatch('/getSessionData') call.

**Comment by visto9259** [comment]
@swaitz 
As mentioned in Discourse, please provide a code example that can reproduce the issue. It will make it easier to figure out what's wrong. 
Thanks

**Comment by swaitz** [comment]
I have created the TestCase which will reproduce the issue.

You only need to extract it and run composer install and then composer test

You should get this result 
![image](https://github.com/user-attachments/assets/a2a87ec7-6cc4-4420-8aac-54ab6153db23)

The "returnContent: Array..." is an dump which I added to see what happens there. I have also added a comment
in the SessionControllerTest.php where I get the wrong data.

I have also removed all the logic which is normally in these files and reduced it to the minimum which is needed.

I hope this helps.

[TestCase.zip](https://github.com/user-attachments/files/16980121/TestCase.zip)

If you have any further questions just ask them.

**Comment by visto9259** [comment]
@swaitz 
Thanks for the test case.

**Comment by froschdesign** [comment]
@swaitz 
Can you [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)? That executed the unit tests are automatically on different PHP versions. See: #82
Thanks in advance! 👍🏻

**Comment by visto9259** [comment]
@froschdesign 
Just for my own contributor education here, you mean create a PR that has the test case code (even if it is 100% different from the base code of laminas-test)?

**Comment by froschdesign** [comment]
@visto9259 
A unit test is required that illustrates the problem. No solution or anything else is required. No ZIP package or a complete application is needed here - just follow the way Git and GitHub works.

**Comment by visto9259** [comment]
> @visto9259 A unit test is required that illustrates the problem. No solution or anything else is required. No ZIP package or a complete application is needed here - just follow the way Git and GitHub works.

@froschdesign 
You lost me here... do you expect @swaitz to fork the laminas-test repo, write a PHPUnit testcase and then PR their change?

**Comment by visto9259** [comment]
@swaitz 
I did some testing with the test case you provided. 

You are effectively calling `$this->dispatch()` twice after the application has been initialized. It's like if your app would init, bootstrap and process two separate requests in one run.  

I think we end up in a situation where the application is not reset to an initial state between two requests as it would if you were running your app in web server.  In real life, the app would go through initialization and bootstraping for each request.  In this test setup, you are not.

The MVC expert can tell me otherwise, but MVC was not designed to do that. In fact, the issue is not within laminas-test but in Laminas\Mvc\Application. After processing one request (`$this->dispatch()`), the application still has all the data and results from that first request when you initiate the second request.  The listener for `Mvc::EVENT_DISPATCH` checks to see if there is a result already and since there is one, it returns and does not call the controller action.

In summary, laminas-test was not designed to do what you want to do the way you want to do it.

**Comment by swaitz** [comment]
@visto9259 
Thank you for checking this. 

> You are effectively calling `$this->dispatch()` twice after the application has been initialized. It's like if your app would init, bootstrap and process two separate requests in one run.

Yes, I know that I'm doing this. Every endpoint in the controllers I have is behind a session check and to test these I have to call my /login endpoint first. This has worked when my project still was on Zend Framework 2 before it was abandoned and renamed to laminas.

>The MVC expert can tell me otherwise, but MVC was not designed to do that. In fact, the issue is not within laminas-test but in Laminas\Mvc\Application. After processing one request ($this->dispatch()), the application still has all the data and results from that first request when you initiate the second request. The listener for Mvc::EVENT_DISPATCH checks to see if there is a result already and since there is one, it returns and does not call the controller action.

I have tried to use the `$this->reset()` method which is available in laminas-test but this also does not help because it destroys the application and the test will fail in the second part where I will test a controller which is behind a session check.

> In summary, laminas-test was not designed to do what you want to do the way you want to do it.

So I should try an think of an other way to test my controllers which are behind a session check?

**Comment by Xerkus** [comment]
Mvc is stateful and heavily leaking state. This was major reason why it couldn't work with any of the approaches that process more than one request per application run.
If you use multiple disptaches during mvc app life you set up yourself for a very problematic bugs, leaks of state and may be even vulnerabilities.

**Comment by swaitz** [comment]
@Xerkus 
Thank you for the insight.

I have it now running and It works as intended. I call now `$this->reset();` before I call a new `$this->dispatch()` for a request which checks the session. 

Maybe something else prevented me from using `$this->reset()` which is as far as I can tell intended to reset the application to make a new request. 

I will close this issue since it was a user error and not a bug.

And thank you all for the help.

**Comment by visto9259** [comment]
May I suggest that, instead of using laminas-test, which is more suited for unit testing, to use other tools like Postman that can automate testing of APIs. It looks like you are doing more end-to-end or integrated testing rather than performing unit testing on controller actions.
